# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'atmadministrativo2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for atmadministrativo2
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'react-native-async-storage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end

  target 'atmadministrativo2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'atmadministrativo2-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for atmadministrativo2-tvOS

  target 'atmadministrativo2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
